package repository

import (
	"database/sql"
	"mimmis/be/internal/model"
)

// FixedCostRepo handles all SQL operations for the fixed_costs table.
type FixedCostRepo struct {
	db *sql.DB
}

func NewFixedCostRepo(db *sql.DB) *FixedCostRepo {
	return &FixedCostRepo{db: db}
}

// Create inserts a new fixed cost. The id is auto-generated by the database (SERIAL)
// and written back into fc.ID via RETURNING.
func (r *FixedCostRepo) Create(fc *model.FixedCost) error {
	return r.db.QueryRow(
		`INSERT INTO fixed_costs (user_id, category_id, apply_day, expense, enabled, note)
		 VALUES ($1, NULLIF($2,''), $3, $4, $5, $6)
		 RETURNING id`,
		fc.UserID, fc.CategoryID, fc.ApplyDay, fc.Expense, fc.Enabled, fc.Note,
	).Scan(&fc.ID)
}

// GetAll returns all fixed cost entries.
func (r *FixedCostRepo) GetAll() ([]model.FixedCost, error) {
	rows, err := r.db.Query(
		`SELECT id, user_id, COALESCE(category_id,''), apply_day, expense, enabled, note
		 FROM fixed_costs ORDER BY apply_day`,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var items []model.FixedCost
	for rows.Next() {
		var fc model.FixedCost
		if err := rows.Scan(
			&fc.ID, &fc.UserID, &fc.CategoryID, &fc.ApplyDay, &fc.Expense, &fc.Enabled, &fc.Note,
		); err != nil {
			return nil, err
		}
		items = append(items, fc)
	}
	return items, rows.Err()
}

// GetByID returns the fixed cost with the given id, or sql.ErrNoRows if not found.
func (r *FixedCostRepo) GetByID(id int32) (*model.FixedCost, error) {
	var fc model.FixedCost
	err := r.db.QueryRow(
		`SELECT id, user_id, COALESCE(category_id,''), apply_day, expense, enabled, note
		 FROM fixed_costs WHERE id = $1`, id,
	).Scan(&fc.ID, &fc.UserID, &fc.CategoryID, &fc.ApplyDay, &fc.Expense, &fc.Enabled, &fc.Note)
	if err != nil {
		return nil, err
	}
	return &fc, nil
}

// Update replaces all mutable fields of the fixed cost entry.
func (r *FixedCostRepo) Update(fc *model.FixedCost) error {
	res, err := r.db.Exec(
		`UPDATE fixed_costs
		 SET user_id=$1, category_id=NULLIF($2,''), apply_day=$3, expense=$4, enabled=$5, note=$6
		 WHERE id=$7`,
		fc.UserID, fc.CategoryID, fc.ApplyDay, fc.Expense, fc.Enabled, fc.Note, fc.ID,
	)
	if err != nil {
		return err
	}
	if n, _ := res.RowsAffected(); n == 0 {
		return sql.ErrNoRows
	}
	return nil
}

// Delete removes the fixed cost entry with the given id.
func (r *FixedCostRepo) Delete(id int32) error {
	res, err := r.db.Exec(`DELETE FROM fixed_costs WHERE id=$1`, id)
	if err != nil {
		return err
	}
	if n, _ := res.RowsAffected(); n == 0 {
		return sql.ErrNoRows
	}
	return nil
}
